# Generated by Django 5.0.6 on 2024-05-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0004_user_passcmd_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
