# Generated by Django 5.0.6 on 2024-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passcmd',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
