# Generated by Django 5.0.6 on 2024-05-29 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0008_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userr',
        ),
    ]
