# Generated by Django 5.0.6 on 2024-05-29 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0009_rename_user_userr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userr',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
