# Generated by Django 5.0.6 on 2024-08-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0012_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
