# Generated by Django 5.0.6 on 2024-08-10 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0013_room_remove_chat_user_chat_room_alter_chat_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
