# Generated by Django 5.0.6 on 2024-08-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0014_remove_chat_response_chat_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rr',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
