# Generated by Django 5.0.6 on 2024-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0015_alter_chat_message_alter_chat_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
    ]
