# Generated by Django 5.0.6 on 2024-09-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0017_category_delete_chat_delete_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
